apiVersion: v1
kind: Namespace
metadata:
  name: ${{ values.namespace }}
  labels:
    app.kubernetes.io/managed-by: rhdh
    environment: ${{ values.environment }}
    team: ${{ values.owner }}
  annotations:
    openshift.io/display-name: "${{ values.appName }} – ${{ values.environment }}"
    openshift.io/description: "${{ values.appDescription }}"
